[WIP] Add Functionality to Text Search Screen
SENG300Iteration3/HISTORY-OF-CANDY pull request #71
Opened 2022-12-07 05:18 UTC by liza-khr

Issues: Crashes when adding item to cart
TextLookupController uses Tuples, while AddItemsScreen uses Objects

2022-12-07 22:07 UTC, calderslom approved these changes
Approved. Ready to add Text Search use case to main

2022-12-07 23:07 UTC, JonUCal submitted a review, later dismissed

2022-12-07 23:36 UTC, calderslom submitted a review, later dismissed

2022-12-07 23:51 UTC, RowanDavitt requested changes
- doing a text search doesn't clear the previous results, so the results pile up

- stuff typed with the gui keyboard is sort of carried across text field (for exampleif you type a password to log in to the attendant station, the password will be added to the item search textfield when you start typing)

- the textfield in item search is still editable

- apparently presentCashScreen is meant to have been deleted



- there are also some unimplemented method errors that should be fixed at some point

- the old hardware directory should be deleted at some point

2022-12-08 01:28 UTC, liza-khr commented
> * doing a text search doesn't clear the previous results, so the results pile up
Fixed
> * stuff typed with the gui keyboard is sort of carried across text field (for exampleif you type a password to log in to the attendant station, the password will be added to the item search textfield when you start typing)
I don't know how to fix this. Since we're low on time I think it's okay to leave it
> * the textfield in item search is still editable
Fixed
> * apparently presentCashScreen is meant to have been deleted
Done
> * there are also some unimplemented method errors that should be fixed at some point
Fixed
> * the old hardware directory should be deleted at some point
Done

2022-12-08 01:45 UTC, RowanDavitt approved these changes

2022-12-08 01:59 UTC, Zevind25 approved these changes

2022-12-08 01:59 UTC, merged